base_config:
  - ./base.yaml

raw_data_dir: ''
processed_data_dir: data/processed/huawei-0304
binary_data_dir: data/binary/huawei-0304
metafile_path: /root/autodl-tmp/SingTechRecog-lrq/data/processed/metadata.json
metafile_wav_root_dir: /mnt/sdb/liruiqi/datasets/huawei_tech
ds_names: 华为男声第一周,华为男声第二周,华为男声第三周,华为女声第一周,华为女声第二周,华为女声第三周,华为女声第四周
ds_names_in_training: ''  # ';' separated
ds_names_in_testing: ''   # default: '', means all in testing
noise_data_dir: /mnt/sdb/liruiqi/SingingDictation/data/binary/musan_24k
# noise_data_dir: ''
binarizer_cls: research.singtech.config.te_binarizer.TechExtractionBinarizer
binarization_args:
  with_wav: true
  with_mel: false
  with_breathiness: false
  with_energy: false
  with_zcr: false

task_cls: research.singtech.te_task.TETask

test_prefixes: [
  "华为女声#假声#单身情歌",
  "华为女声#力度#单身情歌",
  "华为女声#气泡音#单身情歌",
  "华为女声#气声#单身情歌",
  "华为男声#假声#不能说的秘密",
  "华为男声#力度#爱情转移",
  "华为男声#气泡音#安河桥",
  "华为男声#气声#暗香"
]

audio_sample_rate: 24000
fft_size: 512  # Extra window size is filled with 0 paddings to match this parameter
win_size: 512
hop_size: 128
fmin: 30
fmax: 12000
dropout: 0.1
hidden_size: 256

###########
# model related params
###########
model: te
# me5
conformer_kernel: 9
# me8
updown_rates: 2-2-2-2
channel_multiples: 1-1-1-1
bkb_net: conformer   # conv|conformer|transformer|wavenet
bkb_layers: 2
unet_skip_layer: false
unet_skip_scale: 0.7071067812   # 1 / sqrt(2)

###########
# note prediction related hparams
###########
# f0
f0_add_noise: gaussian:0.04  # gaussian:0.04
# pitch
pe: rmvpe  # rmvpe|parselmouth|pw
pe_ckpt: checkpoints/rmvpe/model.pt
f0_bin: 256
f0_filepath: ''
use_pitch_embed: true
# tech
tech_num: 6
tech_threshold: 0.8
#tech_label_smoothing: 0.005
tech_temperature: 0.01
tech_attn_num_head: 4
tech_focal_loss: 5.0
# lambdas
lambda_tech: 1.0
lambdas_tech: ''  # lambdas jointed with '-'
lambda_tech_focal: 3.0

label_pos_weight_decay: 0.95

###########
# noise
###########
noise_snr: 6-20
noise_prob: 0
noise_in_test: false

loud_norm: true
use_mel: true
use_mel_bins: 80
mel_add_noise: gaussian:0.05 # gaussian|none|musan
use_wav: false
use_f0: true
use_breathiness: false
use_energy: false
use_zcr: false
frames_multiple: 16
dataset_downsample_rate: 1.0

lr: 0.000001
scheduler: step_lr
scheduler_lr_step_size: 500
warmup_updates: 0

max_epochs: 1000
max_updates: 240000
max_tokens: 80000
max_sentences: 32
val_check_interval: 500
save_best: true
num_valid_plots: 10
num_valid_stats: 100
accumulate_grad_batches: 4
find_unused_parameters: true
pin_memory: true
ds_workers: 8

torch_compile: false
